#!/bin/bash

# ============================================================
# ELIOS-SAR | PX4 SITL Parameter Setup Helper
# ============================================================
#
# Configures PX4 SITL so that:
# 1. GCS MAVLink loss failsafe is disabled (NAV_DLL_ACT = 0)
# 2. RC loss failsafe is disabled (NAV_RCL_ACT = 0)
# 3. Offboard arming without RC stick is enabled (COM_RC_IN_MODE = 1)
# 4. RC check timeout is bypassed (COM_RCL_EX_T = 0)
#
# This allows ELIOS-SAR to control PX4 purely over ROS 2 / DDS.
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PX4_DIR="${PX4_DIR:-$HOME/PX4-Autopilot}"

echo "============================================================"
echo " Configuring PX4 SITL Parameters for ELIOS-SAR ROS 2 / DDS"
echo "============================================================"
echo "PX4 Directory: $PX4_DIR"

if [ ! -d "$PX4_DIR" ]; then
    echo "WARNING: PX4 directory not found at $PX4_DIR."
    echo "Set PX4_DIR environment variable if installed in a custom location."
    exit 1
fi

CONFIG_DIR="$PX4_DIR/build/px4_sitl_default/rootfs/fs/microsd/etc"
mkdir -p "$CONFIG_DIR"

CONFIG_FILE="$CONFIG_DIR/config.txt"

cat << 'EOF' > "$CONFIG_FILE"
# Auto-generated by ELIOS-SAR setup_px4_params.sh
# Disables GCS & RC checks for pure ROS 2 / DDS offboard flight
param set NAV_DLL_ACT 0
param set NAV_RCL_ACT 0
param set COM_RC_IN_MODE 1
param set COM_RCL_EX_T 0
EOF

echo "✓ Created PX4 SITL startup config at:"
echo "  $CONFIG_FILE"
echo ""
echo "Parameters configured:"
echo "  • NAV_DLL_ACT = 0  (Disable GCS connection requirement)"
echo "  • NAV_RCL_ACT = 0  (Disable RC stick requirement)"
echo "  • COM_RC_IN_MODE = 1  (Allow stickless offboard arming)"
echo "  • COM_RCL_EX_T = 0  (Disable RC loss arming check)"
echo "============================================================"
